services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: wp_local
      MYSQL_USER: wp-user
      MYSQL_PASSWORD: wp-password
      MYSQL_ROOT_PASSWORD: root-password

    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    ports:
      - 8000:80
    restart: always
    volumes:
      - wp-data:/var/www/html/
      - ./wp-dev/themes:/var/www/html/wp-content/themes
      - ./wp-dev/uploads:/var/www/html/wp-content/uploads
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp-user
      WORDPRESS_DB_PASSWORD: wp-password
      WORDPRESS_DB_NAME: wp_local
      WORDPRESS_TABLE_PREFIX: wp_

      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8000');
        define('WP_SITEURL', 'http://localhost:8000');

  wpcli:
    image: wordpress:cli
    container_name: wpcli
    volumes_from:
      - wordpress

    depends_on:
      - wordpress
      - db
    
    command: "--info"
    user: root

    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp-user
      WORDPRESS_DB_PASSWORD: wp-password
      WORDPRESS_DB_NAME: wp_local

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      UPLOAD_LIMIT: 1000M
    restart: always
    depends_on:
      - db
    ports:
      - 8888:80

volumes:
  db_data:
    driver: local

  wp-data:
    driver: local